language: node_js
node_js:
    - 10
    - 12
cache: npm
jobs:
    include:
        - stage: Eslint Verified
          name: 'Eslint Verified'
          install:
              - npm install
              - npm install -g eslint
          script:
              - npm run test

notifications:
    email:
        recipients:
            - travis.ci@spiritling.pub
        on_success: never # default: change
        on_failure: always # default: always
